@startuml Nouveau Client
ClientManagementController -> ClientManagement : doNouveauClient()
ClientManagement -> ClientEditorPane : nouveauClient()
ClientEditorPane -> ClientEditorPaneController : doClientEditorDialog()
ClientEditorPaneController -> Client
Client -> ClientEditorPaneController
ClientEditorPaneController -> ConstantesIHM
ConstantesIHM -> ClientEditorPaneController
ClientEditorPaneController -> Stage : showAndWait()
Stage -> ClientEditorPaneController
ClientEditorPaneController -> ClientEditorPane : return()
ClientEditorPane -> ClientManagement : return()
ClientManagement -> ClientManagementController : return ()
@enduml