= Documentation utilisateur V1 Daily Bank App
XU Anton - GAYRARD Loan - ROBERT Matthieu
v1.0, 16/05/2022 - Equipe 1b1
:toc:
:toc-title: Sommaire
:nofooter:

== Présentation de l'application

Daily Bank App est une application de gestion des comptes clients pour la banque DailyBank. Cette application est à destination des employés de la banque, les guichetiers et les chef d'agences. 

Elle permet aux guichetiers de la banque de gérer et consulter les profils des clients, de créer et gérer des comptes et également de créditer, débiter et éffectuer des virements de compte à comptes. 

Le chef d'agence possède les même fonctionnalité que le guichetier avec quelques possibilité en plus comme rendre inactif un client ou des gérer les différents employés et guichetiers de l'agence.

== Installation et lancement de l'application

Prérequis: Avoir Java 8 installé

Etapes:

    - Télécharger le fichier DailyBankV0.jar
    - Ouvrir le ficheir DailyBankV0.jar en double cliquant dessus


== Utilisation de l'application

=== Explications des différents rôles

Dans cette application, il existe différents rôles qui peuvent effectuer différentes actions. Il y a le guichetiers qui peut éffectuer différentes action de création et de modification sur les clients et les comptes. Il y a le chef d'agence qui peut éffectuer les mêmes actions que le guichetier mais il peut aussi gérer (créer, modifier et supprimer) les guichetiers de l'agence.

=== Fonctionnalités de l'application

==== Créer un client


==== Modifier un client


==== Consulter un compte


==== Débiter un compte


==== Rendre inactif un client

