@startuml Supprimer un prelevement

ComptesManagementController -> ComptesManagement : gererPrelevements()
ComptesManagement -> PrelevementsManagement : doPrelevementsManagementDialog()
PrelevementsManagement -> PrelevementsManagementController : displayDialog()
PrelevementsManagementController -> Stage : showAndWait()
Stage -> PrelevementsManagementController : doSupprimerPrelev()
PrelevementsManagementController -> PrelevementsManagement : supprimerPrelev() 
PrelevementsManagement -> PrelevementEditorPane : doPrelevementEditorDialog()
PrelevementEditorPane -> PrelevementEditorPaneController : displayDialog()
PrelevementEditorPaneController -> Stage : showAndWait()
Stage -> PrelevementEditorPaneController
PrelevementEditorPaneController -> PrelevementEditorPane
PrelevementEditorPane -> PrelevementsManagement
PrelevementsManagement -> AccessPrelevement : deletePrelevement()
AccessPrelevement -> PrelevementsManagement
PrelevementsManagement -> PrelevementsManagementController
PrelevementsManagementController -> PrelevementsManagement
PrelevementsManagement -> ComptesManagement
ComptesManagement -> ComptesManagementController

@enduml