@startuml v2
skinparam actorStyle awesome
left to right direction

actor :Guichetier: as G
actor :Chef d'Agence: as CA

usecase "Modifier infos client" as Info
usecase "Créer un nouveau client" as Nouveau
usecase "Consulter un compte" as Consulter
usecase "Créditer un compte" as Crédit
usecase "Débiter un compte" as Débit
usecase "Créer un compte" as Créer
usecase "Effectuer un virement de compte à compte" as Virement
usecase "Clôturer un compte" as Clôturer
usecase "Générer un relevé mensuel d'un compte en PDF" as pdf
usecase "Gérer les prélèvements automatiques" as prélèvements

usecase "Rendre inactif un client" as Inactif
usecase "Gérer les employés" as Gérer
usecase "Effectuer un Débit exceptionnel" as Debit
usecase "Simuler un emprunt" as Emprunt
usecase "Simuler une assurance d'emprunt" as Assurance


G --> Info
G --> Nouveau
G --> Consulter 
G --> Crédit
G --> Débit
G --> Créer
G --> Virement
G --> Clôturer
G --> pdf
G --> prélèvements

CA --> Inactif
CA --> Gérer
CA --> Debit
CA --> Emprunt
CA --> Assurance

G <|- CA
@enduml